# Generated by Django 3.0.5 on 2020-10-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('desc', models.TextField()),
                ('imdb', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='imagefolder')),
                ('video', models.FileField(upload_to='videofolder')),
            ],
        ),
    ]
