# Generated by Django 3.0.5 on 2021-01-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfolder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='imagefolder'),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='video',
            field=models.FileField(null=True, upload_to='videofolder'),
        ),
    ]
