# Generated by Django 3.0.5 on 2021-01-21 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appfolder', '0002_auto_20210117_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('city_code', models.CharField(max_length=200)),
                ('city_status', models.CharField(default='Active', max_length=200)),
            ],
            options={
                'db_table': 'tbl_city',
            },
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('country_status', models.CharField(default='Active', max_length=255)),
            ],
            options={
                'db_table': 'tbl_country',
            },
        ),
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=200)),
                ('state_code', models.CharField(max_length=200)),
                ('state_status', models.CharField(default='Active', max_length=200)),
                ('country_id', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='appfolder.CountryModel')),
            ],
            options={
                'db_table': 'tbl_state',
            },
        ),
        migrations.CreateModel(
            name='SingupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appfolder.CityModel')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appfolder.CountryModel')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appfolder.StateModel')),
            ],
            options={
                'db_table': 'tbl_singup',
            },
        ),
        migrations.AddField(
            model_name='citymodel',
            name='state_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appfolder.StateModel'),
        ),
    ]
